// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1CU6eNFOv4hDP35nri5fiS6C8g6V-gPQ',
    appId: '1:524369176132:web:695aba25465afabdad3e11',
    messagingSenderId: '524369176132',
    projectId: 'superrecall-3afe5',
    authDomain: 'superrecall-3afe5.firebaseapp.com',
    storageBucket: 'superrecall-3afe5.firebasestorage.app',
    measurementId: 'G-G5LR77ZHBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8wQ1Q21gtVCXLuDYiIIbjqHoEW6Hh7lE',
    appId: '1:524369176132:android:40e609a8cb0ee9a8ad3e11',
    messagingSenderId: '524369176132',
    projectId: 'superrecall-3afe5',
    storageBucket: 'superrecall-3afe5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnmXofjeaQxtM88rxb4jkR8-ofuZnodNU',
    appId: '1:524369176132:ios:fbc472a79b9b5b88ad3e11',
    messagingSenderId: '524369176132',
    projectId: 'superrecall-3afe5',
    storageBucket: 'superrecall-3afe5.firebasestorage.app',
    androidClientId: '524369176132-3tlalt1snavr4dj30go4tamhoft9eup1.apps.googleusercontent.com',
    iosClientId: '524369176132-j4bb09jkrc5egfs2h9kkbalt2ftb23fp.apps.googleusercontent.com',
    iosBundleId: 'com.superrecall.banker',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnmXofjeaQxtM88rxb4jkR8-ofuZnodNU',
    appId: '1:524369176132:ios:fbc472a79b9b5b88ad3e11',
    messagingSenderId: '524369176132',
    projectId: 'superrecall-3afe5',
    storageBucket: 'superrecall-3afe5.firebasestorage.app',
    androidClientId: '524369176132-3tlalt1snavr4dj30go4tamhoft9eup1.apps.googleusercontent.com',
    iosClientId: '524369176132-j4bb09jkrc5egfs2h9kkbalt2ftb23fp.apps.googleusercontent.com',
    iosBundleId: 'com.superrecall.banker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1CU6eNFOv4hDP35nri5fiS6C8g6V-gPQ',
    appId: '1:524369176132:web:ef3085cf457cb94fad3e11',
    messagingSenderId: '524369176132',
    projectId: 'superrecall-3afe5',
    authDomain: 'superrecall-3afe5.firebaseapp.com',
    storageBucket: 'superrecall-3afe5.firebasestorage.app',
    measurementId: 'G-225QG2QMR4',
  );
}
