// AUTO-GENERATED by tools/generate_jaiib_questions.mjs — do not hand-edit.
// Run the generator to (re)populate this file. Merged into the pack by
// tools/ingest_jaiib.mjs alongside the hand-authored QUESTION_BANK.
export const GENERATED_QUESTIONS = [];
